# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jekyll Codex
description: > # this means to ignore newlines until "baseurl:"
  Jekyll Codex wants to make it easier for front-end developers to choose for Jekyll in their next project.
url: "http://jekyllcodex.com" # the base hostname & protocol for your site
permalink: /blog/:title/

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "without-plugin" # a collection in your site, in plural form
    values:
      layout: "without-plugin-item"


# Collections
collections:
  without-plugin:
    output: true
    permalink: /without-plugin/:path/  